general:
  complete_verifier: mip
  enable_incomplete_verification: true
  root_path: ../../applications/pensieve/
  csv_name: capacity_utilization_input100.csv
  device: cpu
model:
  name: pensieve("h64", 41, 2)
  input_shape: [1, 1, 96]
specification:
  conjunctive_output_constraints: True
solver:
  batch_size: 500
  mip:
    solver_threads: 28
    parallel_solvers: 28
    skip_unsafe: false
bab:
  timeout: 600
attack:
  pgd_order: skip
data:
  start: 2
  end: 3