model:
  name: cmars
  input_shape: [1, 1, 38]
specification:
  vnnlib_path: /home/mzi/sys-rl-verif/applications/cmars/vnnlib/plain_comparative/total_range/in19_eps001_out15_0_10.vnnlib
solver:
  batch_size: 8192
  beta-crown:
    iteration: 10
    lr_beta: 0.03
    enable_opt_interm_bounds: False
  # mip:
  #   parallel_solvers: 32
  #   solver_threads: 1
  #   refine_neuron_time_percentage: 0.8
  # start_save_best: -1
  # invprop:
  #   apply_output_constraints_to: ["/input.12"]
bab:
  interm_transfer: true  # Must be true when using both input and relu split.
  pruning_in_iteration: false
  sort_domain_interval: 1
  timeout: 3600
  branching:
    branching_input_and_activation: true
    branching_input_and_activation_order: ["input", "relu"]
    branching_input_iterations: 10
    branching_relu_iterations: 2
    method: kfsb  # For relu split. For input split, smart branching is always used.
    candidates: 5
    reduceop: max
    input_split:
      sb_coeff_thresh: 0.01
attack:
  pgd_order: skip