general:
  enable_incomplete_verification: True
model:
  name: pensieve
  input_shape: [1, 1, 96]
specification:
  vnnlib_path: /home/mzi/sys-rl-verif/applications/pensieve/vnnlib/eps001_0_5.vnnlib
attack:
  pgd_order: skip
solver:
  batch_size: 512
  beta-crown:
    iteration: 10
    enable_opt_interm_bounds: False
  # invprop:
  #   apply_output_constraints_to: ["/input.12"]
bab:
  timeout: 600
  