general:
  enable_incomplete_verification: False
model:
  name: pensieve
  input_shape: [1, 1, 96]
specification:
  vnnlib_path: /home/mzi/sys-rl-verif/applications/pensieve/vnnlib/eps001_0_5.vnnlib
solver:
  batch_size: 2048
  auto_enlarge_batch_size: true
  bound_prop_method: forward+crown
  # bound_prop_method: alpha-crown
  alpha-crown:
    share_alphas: true
  beta-crown:
    iteration: 10
bab:
  initial_max_domains: 1000
  timeout: 36000
  branching:
    method: sb
    input_split:
      enable: True
      adv_check: .inf
      sb_coeff_thresh: 0.1
      split_partitions: 20
      # writer_path: "results/log/pensieve/input_plain_20partition_"
      # if_repetition: True
      # if_split_only_copy_one: False
attack:
  pgd_order: input_bab