general:
  enable_incomplete_verification: False
  root_path: ../../applications/cmars  # Please clone the vnncomp2021 repo first as it contains the benchmark.
  csv_name: instances_10partition.csv
  # complete_verifier: skip
model:
  name: cmars
  input_shape: [1, 1, 38]
solver:
  batch_size: 2048
  auto_enlarge_batch_size: true
  bound_prop_method: forward+crown
bab:
  initial_max_domains: 1000
  timeout: 3600
  branching:
    method: sb
    input_split:
      enable: True
      adv_check: .inf
      sb_coeff_thresh: 0.1
      split_partitions: 20
      writer_path: "results/log/10_partition/"
      if_repetition: True
attack:
  pgd_order: input_bab