model:
  name: cmars
  input_shape: [1, 1, 38]
specification:
  vnnlib_path: /home/mzi/sys-rl-verif/applications/cmars/vnnlib/plain_comparative/in19_eps001_out15_0_14.vnnlib
attack:
  pgd_order: skip
solver:
  batch_size: 8192
  beta-crown:
    iteration: 20
bab:
  timeout: 600
  cut:
    enabled: True
    cplex_cuts: True
    bab_cut: True
    lr_decay: 0.9